### ISSUE TITLE
i can't find the Rmd files

### ISSUE THREAD

**Issue by andreashandel** [epid8060fall2019/TrangQuach-Project#1]
i can't find the Rmd file(s) to reproduce your results. Where are they located? Did you make sure to push them to the repository?

**Comment by TrangQuach** [comment]
Dear Dr. Handel, 

I am sorry for late response. You can find my Rmd files to reproduce my results in this directory: TrangQuach-Project\code\processing_code. 

In processing code:
ProcessingWork: RDATA file to save the workspace
ProcessingScript: R file contains all of my code
index Rmd: Rmd file contain all of my code

ProcessingScript and index Rmd are the same file, but just difference in type of file (Rmd or R file).
I write the code in R file first. Then, I want to create a report to you, so I create this code again in Rmd file. 

I understand that I need to create a reproducible work. So, I create a R project and use code to import data which does not contain the directory specific to my computer. You can see that in my ProcessingScript.
However, in index Rmd file, my code to import data has to contain the directory specific to my computer. This is because it get errors when I do not use the directory which is specific to my computer. I do not know why it happens. If you have any idea about this issue, please let me know.

Thank you.

**Comment by andreashandel** [comment]
I'll take another look. I suggest for any data loading (and saving things), use the 'here' package. See my post about that on eLC. That should fix any problems with paths. There should not be any local paths that only exist on your computer.

**Comment by TrangQuach** [comment]
Thank you so much. I searched around on google for some hours, but I still cannot fix the issue.
Your suggestion is so so helpful. I am able to fix the issue. I really appreciate your help.
